### ISSUE TITLE
Implement a SPA front-end

### ISSUE THREAD

**Issue by judibo** [herbsjs/todolist-on-herbs#11]
Create a simple SPA to start consume the API and have a nice UI.
Should it be a completely separate project or a directory on the root folder works (back-end/front-end)?

**Comment by jhomarolo** [comment]
Despite being in favor of separating the repositories, for a number of reasons such as: ease of deployment, ease of development by several teams, etc, I think we could evolve the entire project here in this repository, at least in the beginning. 

Even more that the front will only exist to cover the functionality of the backend and vice versa.
