### ISSUE TITLE
The items inside list are not returning inside route /lists

### ISSUE THREAD

**Issue by jhomarolo** [herbsjs/todolist-on-herbs#124]
**Describe the bug**
When accessing the route /lists (get all lists) only the lists are returned but not the items inside the lists.

**To Reproduce**
Run localy and access the route http://localhost:4000/lists

**Comment by mtperesvx** [comment]
Hi, 
We can work on this issue. 

@danilokatayama

**Comment by crtotta** [comment]
I work on this

**Comment by vitorgamer58** [comment]
Getting the same problem here, in GraphQL, I got an empty array, even though I had items in the list.

```
{
  "data": {
    "getItems": [
      {
        "id": 34774,
        "description": "Criar o site",
        "isDone": null,
        "position": 1
      },
      {
        "id": 95191,
        "description": "Criar o site",
        "isDone": null,
        "position": 2
      },
      {
        "id": 80996,
        "description": "Criar o site",
        "isDone": null,
        "position": 3
      },
      {
        "id": 49524,
        "description": "Criar o site",
        "isDone": null,
        "position": 4
      },
      {
        "id": 61855,
        "description": "Criar o site",
        "isDone": null,
        "position": 5
      }
    ],
    "getLists": [
      {
        "id": 59476,
        "name": "programar",
        "items": []
      }
    ]
  }
}
```

**Comment by dalssoft** [comment]
@crtotta are still working on it?

**Comment by CrizanTottaVx** [comment]
@dalssoft Yes, but I still haven't found a solution.

**Comment by vitorgamer58** [comment]
O banco de dados de listas não possui uma coluna com o nome "itens", por isso quando o programa pede todas as listas, o item "itens" virá como undefined.
https://github.com/herbsjs/todolist-on-herbs/blob/main/src/domain/usecases/getLists.js#L33
Então a entidade define para ele o seguinte valor padrão: `[]`
Por isso os itens é um array vazio, **desconheço a melhor estratégia de resolver isso**, tentei com um forEach, para buscar no banco de dados os itens para cada lista existente, mas sem sucesso.
![Screenshot_6951](https://user-images.githubusercontent.com/8906065/181405208-04060030-b0e8-41a6-88dd-6fb5e3157692.png)
Obtive um erro no retorno da chamada de api:
```
{
    "error": "TypeError",
    "message": "undefined is not iterable (cannot read property Symbol(Symbol.iterator))"
}
```
Apesar de no console.log os itens aparecerem.

**Comment by dalssoft** [comment]
As I understand this problem:

- for REST, I'm not sure the microservice should bring the list of items. The resource is `List`.

- for GraphQL, I think the GraphQL engine should know that it would be necessary to call an extra resolver / use case (GetItens) to be able to get the items from a list.

We should understand why it is not happening with GraphQL.

**Comment by vitorgamer58** [comment]
> As I understand this problem:
> 
> * for REST, I'm not sure the microservice should bring the list of items. The resource is `List`.
> * for GraphQL, I think the GraphQL engine should know that it would be necessary to call an extra resolver / use case (GetItens) to be able to get the items from a list.
> 
> We should understand why it is not happening with GraphQL.

I solved the issue with a for loop: https://github.com/herbsjs/todolist-on-herbs/pull/147
But I don't know if this is the right way.
