### ISSUE TITLE
Layout and Design

### ISSUE THREAD

**Issue by endersoncosta** [herbsjs/todolist-on-herbs#13]
I believe that the project can include a simple layout with a good design, but that shows the real potential of the project.

**Comment by endersoncosta** [comment]
I like of the Microsoft To Do Design, it's clean and with a simple use. 

Follow a image to you see:
![image](https://user-images.githubusercontent.com/6051663/81746090-47391400-947c-11ea-9b75-3b4680e04ef8.png)

**Comment by maikmb** [comment]
Hi @endersoncosta !
I also like this layout!

**Comment by endersoncosta** [comment]
I am planning to use the material ui, because the _"Responsive Drawer"_ fits what I thought for the design.

Links to reference:
[Material Ui Drawers](https://material-ui.com/pt/components/drawers/)
[Material Ui Responsive Drawer Sandbox](https://codesandbox.io/s/6khtm)

**Comment by jhomarolo** [comment]
Hello @endersoncosta, as soon as you have a layout proposal please share it with us.

**Comment by endersoncosta** [comment]
Yes of course, soon as possible I want to make this implementation.

**Comment by endersoncosta** [comment]
I implemented a basic structure, so that over time we can improve and add features.
