### ISSUE TITLE
What about herbs CLI ?

### ISSUE THREAD

**Issue by italojs** [herbsjs/todolist-on-herbs#50]
# Herbs CLI
Inspired by [VueJS](https://cli.vuejs.org/), [Angular](https://cli.angular.io/), [dotnet](https://docs.microsoft.com/pt-br/dotnet/core/tools/) and others,  I would like to suggest the creation of a CLI  to help the new herbs adopters

Usually developer use CLIs to easily start an project and principally the jr developers use it to maintain the project in the same architecture proposed by the framework. 

The main idea of this CLI is to facilitate the creation of new projects and modules in your project that use herbs. In the future I believe this CLI can be an tool to check your herbs quality code, help you to modeling your clean archtecture, analisy logs and more, but **for now** it will start being something like a semi-inteligent code generator.

### Propose 1
My initial propose is to build an entry project by the CLI like an template

`Herbs new app -—graphql -—knex-pg`  (We can use --rest --mongo --knex-sql-server and other)

This will create an app with graphql that use a knex-repository, the generated files will be something like this:

```
│   ├── herbs.json
│   ├── index.js
│   ├── knexfile.js
│   ├── package.json
│   └── src
│       ├── domain
│       │   ├── entities
│       │   │   ├── entity.js
│       │   │   ├── entity.test.js
│       │   └── usecases
│       │       ├── createEntity.js
│       │       ├── createEntity.test.js
│       │       ├── deleteEntity.js
│       │       ├── deleteEntity.test.js
│       │       ├── getEntity.js
│       │       ├── getEntity.test.js
│       │       ├── updateEntity.js
│       │       └── updateEntity.test.js
│       └── infra
│           ├── api
│           │   ├── graphql
│           │   │   ├── custom
│           │   │   ├── defaultResolver.js
│           │   │   ├── defaultResolver.test.js
│           │   │   ├── index.js
│           │   │   ├── mutations.js
│           │   │   ├── queries.js
│           │   │   └── types.js
│           │   └── server.js
│           ├── config
│           │   ├── config.js
│           ├── db
│           │   └── migrations
│           │       ├── 20210101000000_entity.js
│           ├── repl
│           │   └── index.js
│           └── repositories
│               ├── memDB
│               │   ├── inMemDB.js
│               │   ├── EntityRepository.js
│               │   ├── EntityRepository.test.js
│               └── pg
│                   ├── connection.js
│                   ├── EntityRepository.js
```

note we have an `herbs.json`, this json will be an control file to help the cli when it add new modules in the project.

### Propose 2 
my second propose is to build an modular project, so the first thing you need is to create your entities int the root project path:
```
├── user.js
├── item.js
```

so when we start our project we can generate all project using the entities
` Herbs new app -—graphql —-knex `

This will create an app with graphql that use knex into repository, the generated files will be something like this:

```
│   ├── herbs.json
│   ├── index.js
│   ├── knexfile.js
│   ├── package.json
│   └── src
│       ├── domain
│       │   ├── entities
│       │   │   ├── user.js
│       │   │   ├── user.test.js
│       │   └── usecases
│       │       ├── createUser.js
│       │       ├── createUser.test.js
│       │       ├── deleteUser.js
│       │       ├── deleteUser.test.js
│       │       ├── getUser.js
│       │       ├── getUser.test.js
│       │       ├── updateUser.js
│       │       └── updateUser.test.js
│       │       ├── createItem.js
│       │       ├── createItem.test.js
│       │       ├── deleteItem.js
│       │       ├── deleteItem.test.js
│       │       ├── getItem.js
│       │       ├── getItem.test.js
│       │       ├── updateItem.js
│       │       └── updateItem.test.js
│       └── infra
│           ├── api
│           │   ├── graphql
│           │   │   ├── custom
│           │   │   ├── UserResolver.js
│           │   │   ├── UserResolver.test.js
│           │   │   ├── ItemResolver.js
│           │   │   ├── ItemResolver.test.js
│           │   │   ├── index.js
│           │   │   ├── mutations.js
│           │   │   ├── queries.js
│           │   │   └── types.js
│           │   └── server.js
│           ├── config
│           │   ├── config.js
│           ├── db
│           │   └── migrations
│           │       ├── 20210101000000_User.js
│           │       ├── 20210101000000_item.js
│           ├── repl
│           │   └── index.js
│           └── repositories
│               ├── memDB
│               │   ├── inMemDB.js
│               │   ├── UserRepository.js
│               │   ├── UserRepository.test.js
│               └── pg
│                   ├── connection.js
│                   ├── UserRepository.js
│                   ├── UserRepository.test.js
│               │   ├── ItemRepository.js
│               │   ├── ItemRepository.test.js
```

note we have an `herbs.json`, this json will be an control file to help the cli when it add new modules in the project.

### Propose 3

Makes the propose-1 so grow the CLI to propose-2

# Herbs Modules

After create your app,  you can write an new entity in the project and generate a new crud for this entity, example:
`herbs new entity ShoppingCart`(or you can specify the entity path with --path)
So we will in the entities path `src/entities/item.js, read the file and generate a CRUD usecase (create, delete, list, update), generate the repository and add this entity into graphql layer.
 
```
│   ├── herbs.json
│   ├── index.js
│   ├── knexfile.js
│   ├── package.json
│   └── src
│       ├── domain
│       │   ├── entities
│       │   │   ├── user.js
│       │   │   ├── user.test.js
│       │   └── usecases
│       │       ├── createUser.js
                [...]
│       │       ├── createItem.js
│       │       [...]
                ├── createShoppingCart.test.js
│       │       ├── deleteShoppingCart.js
│       │       ├── deleteShoppingCart.test.js
│       │       ├── getShoppingCart.js
│       │       ├── getShoppingCart.test.js
│       │       ├── updateShoppingCart.js
│       │       └── updateShoppingCart.test.js
│       └── infra
│           ├── api
│           │   ├── graphql
│           │   │   ├── custom
                    [...]
│           │   │   ├── ShoppingCart.js
│           │   │   ├── ShoppingCart.test.js
│           │   │   ├── index.js
│           │   │   ├── mutations.js
│           │   │   ├── queries.js
│           │   │   └── types.js
│           │   └── server.js
│           ├── config
│           │   ├── config.js
│           ├── db
│           │   └── migrations
                    [...]
│           │       ├── 20210101000000_ShoppingCart.js
│           ├── repl
│           │   └── index.js
│           └── repositories
│                   memDB
│                   ├── inMemDB.js
                    [...]
│                   ├── 20210101000000_ShoppingCart.js
│                   pg
│                   ├── connection.js
│                   ├── UserRepository.js
│                   ├── UserRepository.test.js
│                   ├── ItemRepository.js
│                   ├── ShoppingCartRepository.test.js
│                   ├── ShoppingCartRepository.test.js
```

other example is to create new presentation layer
`herbjs new module --rest` 

so we add the herbs2rest into package.json and generate the rest layer

I believe we can have the commands:

**beta stage**
`herbs new app < --graphql --rest --knex --mongo >`

**release 1.0**
`herbs add layer < --graphql --rest --knex --mongo >` 
`herbs add entity <name or --path>`

**Comment by BritoDoug** [comment]
I think that's a very good idea, a little bit complex, but will cut a lot of time from simple demands, and is awesome to show in community presentation, begin a Herbs project in five minutes... hype

**Comment by dalssoft** [comment]
It seems Propose 1 and 2 does not compete.

P1 - Create a initial folder structure and setup
P2 - Been able to create a CRUD based on a pre-existing entity

For me an evolutive CLI would be something like that:

- Create default folder structure and pre-setup env
	- Been able to choose the glues you need
- Been able to add an entity using CLI
- Been able to add a use case using CLI
- Been able to add a new glue (ex: add REST)
- Been able to add a use case based on a pre-existing entity

**Comment by jhomarolo** [comment]
I think the CLI could be intuitive, when a user types herbs start, an options menu would appear for example.

I really like the model that yeoman.io makes.

![](https://github.com/yeoman/yo/raw/main/screenshot.png)

**Comment by dalssoft** [comment]
How is it going with this project @italojs? Need help?
