### ISSUE TITLE
This example project must to be generated with herbs-cli?

### ISSUE THREAD

**Issue by italojs** [herbsjs/todolist-on-herbs#63]
I think this example app must to be generated with our [herbs-cli](https://github.com/herbsjs/herbs-cli) ooor the example app must to be inside herbs-cli repository into an example folder

**Comment by italojs** [comment]
test

**Comment by jhomarolo** [comment]
IMHO no. This project shows what a microservice closer to the real world would look like with various custom configurations, etc.

The cli is just a simple quick launch project for any kind of project.

**Comment by dalssoft** [comment]
@italojs I think we can generate this project using CLI but, as mentioned by @jhomarolo, we should find a way to keep the custom examples.
